### ISSUE TITLE
database

### ISSUE THREAD

**Issue by TashKiriri** [detronetdip/E-commerce#19]
Why is it giving me this error Fatal error: Uncaught mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\Ecommerce\utility\connection.php:4 Stack trace: #0 C:\xampp\htdocs\Ecommerce\utility\connection.php(4): mysqli_connect('localhost', 'root', Object(SensitiveParameterValue)) #1 C:\xampp\htdocs\Ecommerce\utility\utility.php(2): require('C:\\xampp\\htdocs...') #2 C:\xampp\htdocs\Ecommerce\Admin\require\top.php(2): require('C:\\xampp\\htdocs...') #3 C:\xampp\htdocs\Ecommerce\Admin\index.php(2): require('C:\\xampp\\htdocs...') #4 {main} thrown in C:\xampp\htdocs\Ecommerce\utility\connection.php on line 4

**Comment by detronetdip** [comment]
Did you spin up the project using docker compose?

**Comment by asyrofist** [comment]
well, I try same too.. so I change 127.0.0.1 as localhost to 0.0.0.0 for docker-compose purposes..
